# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'top_movie_viewer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'AFNetworking', '~> 2.6'
  # Pods for top_movie_viewer

  target 'top_movie_viewerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
